spec_class = "training_wizard.recipes.modular.ModularTrainingSpec"
validation = 5

[wizard_module]
spec_class = "training_wizard.specs.modules.instruction_tune.InstructionTuningModule"
eval_sample_size = 100

[wizard_module.transformer_spec]
pretrained_name = "llamafactory/tiny-random-Llama-3"

[wizard_module.transformer_spec.tokenizer_call_kwargs]
max_length = 512
truncation = true

[dataset_spec]
spec_class = "training_wizard.specs.dataset.TemplateInstructDatasourceSpec"
output_column = "messages"

[[dataset_spec.messages_template]]
role = "system"
content = """You are multilingual paraphraser. Always answer with a paraphrase of the user's input."""

[[dataset_spec.messages_template]]
role = "user"
content = """{source}"""

[[dataset_spec.messages_template]]
role = "assistant"
content = """{target}"""

[dataset_spec.parent]
spec_class = "training_wizard.specs.dataset.SimpleDataSourceSpec"
data_files = "examples/data/seq2seq.jsonl"

[training_args_spec]
run_name = "Paraphraser Qwen2.5 Instruct 0.5B"
output_dir = "examples/instruction_tuning/output"
warmup_steps = 2500
num_train_epochs = 1
per_device_train_batch_size = 2
per_device_eval_batch_size = 2
bf16 = true
optim = "adamw_bnb_8bit"
learning_rate = 1e-5
gradient_checkpointing = true
neftune_noise_alpha = 5
torch_compile = true

[callbacks_spec]
enable_early_stopping = true
early_stopping_patience = 2
evaluate_first_step = false
