spec_class = "training_wizard.recipes.modular.ModularTrainingSpec"
validation = 6

[wizard_module]
spec_class = "training_wizard.specs.modules.seq_cls.SequenceClassifierModule"
loss_type = "cross_entropy"
label_smoothing = 0.0
compute_eval_metrics = true

[wizard_module.transformer_spec]
pretrained_name = "microsoft/deberta-v3-xsmall"

[wizard_module.transformer_spec.from_pretrained_kwargs]
num_labels = 2

[wizard_module.transformer_spec.tokenizer_call_kwargs]
max_length = 256
truncation = true

[dataset_spec]
spec_class = "training_wizard.specs.dataset.SimpleDataSourceSpec"
data_files = "examples/data/sequence_classification.tsv"
load_dataset_kwargs = { sep = "\t" }
loader = "csv"

[training_args_spec]
output_dir = "examples/sequence_classification/output"
run_name = "My Example Sequence Classifier"
num_train_epochs = 1
warmup_steps = 200
logging_steps = 50
per_device_train_batch_size = 2
per_device_eval_batch_size = 2
bf16 = true
fp16 = false
optim = "adamw_bnb_8bit"
learning_rate = 1e-5
weight_decay = 0.0
gradient_accumulation_steps = 1
gradient_checkpointing = false
save_only_model = true

[callbacks_spec]
enable_early_stopping = true
early_stopping_patience = 3
evaluate_first_step = true
